#
# ~/.bashrc
#

eval "$(oh-my-posh --init --shell bash --config ~/.slowlydev.omp.json)"

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '
